In [2]:
import numpy as np

In [3]:
# Creating 1d array
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [4]:
type(a)

numpy.ndarray

In [5]:
print(a+b)
print(a-b)
print(a*b)


[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [6]:
# Creating 2d array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [7]:
# Creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [8]:
# Tells no. of rows and columns
print(a2.shape)
print(a3.shape)

(2, 3)
(3, 2, 3)


In [9]:
# Tells the dimension of the array
print(a2.ndim)
print(a3.ndim)

2
3


In [10]:
# Tells the datatype present in an array
print(a2.dtype)

int64


In [11]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.random.randint(1,11, size=(2,3))

array([[ 3,  9,  2],
       [10,  1,  2]], dtype=int32)

In [15]:
np.random.randint(1,11, size=(3,2,3))

array([[[ 3, 10,  7],
        [10,  9,  5]],

       [[ 8,  5,  3],
        [ 5,  4,  7]],

       [[ 6,  6,  8],
        [ 5,  8, 10]]], dtype=int32)

In [16]:
x = np.random.randint(1,21, size=(2,2))
y = np.random.randint(1,21, size=(2,2))
print(x)
print(y)

[[11 12]
 [ 8  3]]
[[13  4]
 [13 16]]


In [17]:
print(x+y)
print(x-y)
print(x*y) # Element multiplication

[[24 16]
 [21 19]]
[[ -2   8]
 [ -5 -13]]
[[143  48]
 [104  48]]


In [18]:
# Matrix multiplication
# 1st method
print(x @ y)

[[299 236]
 [143  80]]


In [19]:
# 2nd method
np.dot(x,y)

array([[299, 236],
       [143,  80]], dtype=int32)

In [20]:
x.prod()

np.int64(3168)

In [21]:
x.mean()


np.float64(8.5)

In [22]:
y.mean()


np.float64(11.5)

In [23]:
print(x)

[[11 12]
 [ 8  3]]


In [24]:
b = x.mean(axis=0) #column wise
print(b)

[9.5 7.5]


In [25]:
c = x.mean(axis=1) #row wise
print(c) 

[11.5  5.5]


In [26]:
print(x.sum())
print(x.std()) # standard deviation
print(x.var()) # variance

34
3.5
12.25


In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9,])
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))


5.0
3.0
7.0


In [28]:
arr2 = np.random.randint(11,100, (4,4))
print(arr2)

[[75 95 94 84]
 [59 45 73 19]
 [75 44 62 96]
 [86 73 40 18]]


In [29]:
# To convert a matrix from one to another
print('2*8')
print(arr2.reshape(2,8))
print('8*2')
print(arr2.reshape(8,2))

2*8
[[75 95 94 84 59 45 73 19]
 [75 44 62 96 86 73 40 18]]
8*2
[[75 95]
 [94 84]
 [59 45]
 [73 19]
 [75 44]
 [62 96]
 [86 73]
 [40 18]]


In [30]:
print(arr2)

[[75 95 94 84]
 [59 45 73 19]
 [75 44 62 96]
 [86 73 40 18]]


In [34]:
# indexing
print(arr2[0]) # index position of 0th row
print(arr2[0,1]) # 0 row mein first index i.e. 0th row 1st column
print(arr2[-1]) # last row
# slicing
print(arr2[:3]) # 0th to second row
print(arr2[1:]) # 1st to last row

[75 95 94 84]
95
[86 73 40 18]
[[75 95 94 84]
 [59 45 73 19]
 [75 44 62 96]]
[[59 45 73 19]
 [75 44 62 96]
 [86 73 40 18]]


In [35]:
arr2 >50

array([[ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True, False,  True,  True],
       [ True,  True, False, False]])

y = arr2[arr2>50]
z = y.reshape(4,2)
print(z)